AWSTemplateFormatVersion: '2010-09-09'
Description: archconf-s3

Resources:

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Action:
            - s3:GetObject
            Effect: Allow
            Resource: !Sub "${Bucket.Arn}/*"
            Principal: "*"
          - Action:
            - s3:GetObject
            Effect: Deny
            Resource: !Sub "${Bucket.Arn}/secure/*"
            NotPrincipal:
              AWS: !Join ["", ["arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ", !ImportValue OriginAccessIdentity]]

Outputs:
  BucketArn:
    Value: !GetAtt Bucket.Arn
    Export:
      Name: BucketArn
  BucketUrl:
    Value: !GetAtt Bucket.WebsiteURL
    Export:
      Name: BucketUrl
  BucketDomain:
    Value: !GetAtt Bucket.DomainName
    Export:
      Name: BucketDomain
