AWSTemplateFormatVersion: '2010-09-09'
Description: archconf-certificate

Parameters:
  ValidationDomain:
    Type: String
    Default: symphonia.io

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !ImportValue DomainName
      SubjectAlternativeNames:
        - !Join ['.', ['*', !ImportValue DomainName]]
      DomainValidationOptions:
        - DomainName: !ImportValue DomainName
          ValidationDomain: !Ref ValidationDomain

Outputs:
  CertificateArn:
    Value: !Ref Certificate
    Export:
      Name: CertificateArn
