AWSTemplateFormatVersion: '2010-09-09'
Description: oscon-cloudfront

Resources:

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - Id: S3Origin
          DomainName: !Select [1, !Split ['://', !ImportValue BucketUrl]]
          CustomOriginConfig:
            OriginProtocolPolicy: http-only
        Enabled: 'true'
        DefaultRootObject: index.html
        Aliases:
          - !ImportValue DomainName
          - !Join ['.', ['www', !ImportValue DomainName]]
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: allow-all
          Compress: true
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !ImportValue CertificateArn
          SslSupportMethod: sni-only

Outputs:
  CloudFrontDomain:
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: CloudFrontDomain
