AWSTemplateFormatVersion: '2010-09-09'
Description: oscon-route53

Parameters:
  DomainName:
    Type: String
    Default: oscon.symphonia.io

Resources:

  RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Join ['', [!Ref DomainName, '.']]
      RecordSets:
      - Name: !Ref DomainName
        Type: A
        AliasTarget:
          DNSName: !ImportValue CloudFrontDomain
          HostedZoneId: Z2FDTNDATAQYW2
      - Name: !Join ['.', ['www', !Ref DomainName]]
        Type: A
        AliasTarget:
          DNSName: !ImportValue CloudFrontDomain
          HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  Domain:
    Value: !Ref DomainName
    Export:
      Name: DomainName
